### ISSUE TITLE
ahhh

### ISSUE THREAD

**Issue by Caylaaa18** [steelbrain/PDO-Mysql#10]
[ Private Message removed by steelbrain ]

**Comment by steelbrain** [comment]
wtf, this is gh, don't abuse it for PM purposes

**Comment by Caylaaa18** [comment]
Then listen to me! and read what i age to say on skype

**Comment by Caylaaa18** [comment]
I'm sorry, I wasn't able to tell you that i was losing connection. By the time i tried to tell you i already did, and i've been trying for the past almost hour trying to get some type of wifi so i can talk to you and clarify what happened

**Comment by Caylaaa18** [comment]
ugh i have to go, i'll try to contact you later

**Comment by Caylaaa18** [comment]
@steelbrain  yo are you going to grow up and talk to me or continue to be a hypocrite??
